name: Feedback Report
description: File a feedback report
title: "M00-LAB00: QUICK_DESCRIPTION"
labels: ["feedback"]
body:
  - type: markdown
    attributes:
      value: |
        # Thanks for taking the time to fill out this feedback report!
        
        **Replace feedback name LAB00:QUICK_DESCRIPTION, for example "LAB01: My new feedback"**
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info 😉?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What should we change?
      description: What should we change?
      placeholder: Tell us your proposal!
      value: PROPOSAL
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Lab
      description: Lab name
      options:
        - Other
        - Lab 00 Validate lab environment
        - Lab 01 Agile planning and portfolio management with Azure Boards
        - Lab 02 Version controlling with Git in Azure Repos
        - Lab 03 Version controlling with Git in Azure Repos
        - Lab 04 Configuring agent pools and understanding pipeline styles
        - Lab 05 Enabling continuous integration with Azure Pipelines
        - Lab 06 Integrating external source control with Azure Pipelines
        - Lab 07 Implementing GitHub Actions by using DevOps Starter
        - Lab 08 Deploying Docker Containers to Azure App Service web apps
        - Lab 09 Control Deployments using Release Gates
        - Lab 10 Creating a release dashboard
        - Lab 11 Configuring pipelines as code with YAML
        - Lab 12 Setting up and running functional tests
        - Lab 13 Integrate Azure Key Vault with Azure DevOps
        - Lab 14 Azure deployments using Azure Resource Manager templates
        - Lab 15 Implement security and compliance in Azure DevOps Pipelines
        - Lab 16 Managing technical debt with SonarQube and Azure DevOps
        - Lab 17 Package management with Azure Artifacts
        - Lab 18 Monitoring application performance with Application Insights
        - Lab 19 Integration between Azure DevOps and Microsoft Teams
        - Lab 20 Sharing Team Knowledge using Azure Project Wikis
    validations:
      required: true
  - type: textarea
    id: Screenshots
    attributes:
      label: Relevant screenshots
      description: Please copy and paste any relevant screenshots 📸
      value: paste here 😉 
  
